

services:
  client:
    build: .
    environment:
      - SERVER_IP=${SERVER_IP:-host.docker.internal}
      - SERVER_PORT=${SERVER_PORT:-5200}
      
      # Necessario per i container Docker per renderizzare la grafica (X11) sull'host
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    
  