

services:
  server:
    build: .
    container_name: tris_server
    ports:
      - "${PORT:-5200}:${PORT:-5200}"
    environment:
      - PORT=${PORT:-5200}
    restart: unless-stopped #si riavvia a meno che non venga fermato manualmente
